### ISSUE TITLE
FeyTweaks on 1.20.4

### ISSUE THREAD

**Issue by OPISOF** [feytox/FeyTweaks#17]
Hello! Can you update your mod to 1.20.4? Your mod is very good for optimization.

**Comment by feytox** [comment]
Hello. Okay, I'll port the mod to 1.20.4 soon.

**Comment by feytox** [comment]
https://modrinth.com/mod/feytweaks/version/1.20.4-1.2.8

**Comment by OPISOF** [comment]
Thanks
