### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by BlueGradientHorizon** [feytox/FeyTweaks#18]
Hello. Can you update FeyTweaks mod to 1.20.6, please?

**Comment by feytox** [comment]
Hello. The mod will be updated in the next few days, because I am currently a little busy.

**Comment by BlueGradientHorizon** [comment]
Great, thank you

**Comment by feytox** [comment]
Updated the mod yesterday, but forgot to post a link here.
https://modrinth.com/mod/feytweaks/version/1.20.6-1.2.8
