### ISSUE TITLE
Enhancement: render sign text at low resolution when too many signs / fps too low

### ISSUE THREAD

**Issue by Kirisoup** [feytox/FeyTweaks#3]
Your mod is amazing at optimizing signs, especially glowing signs! This issue does not occure when playing with the defaut font, so it's not an actual issue but maybe a possible enhancement?

If playing with a high-res font pack, lag could build up quite dramatically when large amount of signs are present

Compare: Vanilla and custom font
![image](https://user-images.githubusercontent.com/94152497/208247323-64504f33-b9d3-438d-9f86-ec7a43f01b0f.png)
![image](https://user-images.githubusercontent.com/94152497/208247415-c12ae644-f80f-4c36-880d-a466b98c323a.png)

**Comment by feytox** [comment]
Can you name a mod, resource pack, etc. that changes the font to this one?  This will help me try to fix the bug.

**Comment by feytox** [comment]
Re-open the issue if you have something new on this bug.
