### ISSUE TITLE
mc crashes when using sign?

### ISSUE THREAD

**Issue by MaxxusX** [feytox/FeyTweaks#5]
don't know if this is causing it 

[crash-2022-12-26_21.40.30-client.txt](https://github.com/feytox/FeyTweaks/files/10305756/crash-2022-12-26_21.40.30-client.txt)

**Comment by feytox** [comment]
Do you have a mod called "replaceitem", "symbolchat" or similar that changes the rendering of the signs or changes them?  If so, please tell me the name of this mod as it is incompatible with FeyTweaks sign optimizations.

**Comment by Fleepe** [comment]
Is FeyTweaks compatible with Enhanced Block Entities ?

**Comment by feytox** [comment]
> Is FeyTweaks compatible with Enhanced Block Entities ?

FeyTweaks is incompatible with those EBE settings that modify the signs. With the mod itself, at least before, there were no conflicts.

**Comment by feytox** [comment]
Open a new issue if new crashes occur.
