### ISSUE TITLE
Package name not updated in fabric.mod.json

### ISSUE THREAD

**Issue by unilock** [feytox/FeyTweaks#7]
https://github.com/feytox/FeyTweaks/blob/f4d5b6229d1c2d33fe7528c06395a0625d910331/src/main/resources/fabric.mod.json#L24

Thus the mod fails to load :)

```
java.lang.ClassNotFoundException: name.uwu.feytox.feytweaks.Feytweaks
```

**Comment by feytox** [comment]
oh sorry, didn't notice that error. I'll post a hotfix in a couple of minutes.
