### ISSUE TITLE
does not work on 1.19.4

### ISSUE THREAD

**Issue by xMimicria** [feytox/FeyTweaks#8]
the mod doesn't work on meincraft 1.19.4
put on a clean build only with sodium, and the result is the same
![image](https://github.com/feytox/FeyTweaks/assets/92284789/d2f44ff4-4292-4c42-9212-7f802c88ff76)

**Comment by feytox** [comment]
Судя по субтитрам, я могу обращаться к вам на русском.

Текст на табличках пропадает совсем или пропадает на расстоянии? Если на расстоянии, то в этом и есть суть мода. Чтобы настроить скрывание табличек, используйте конфиг через Mod Menu.

**Comment by xMimicria** [comment]
Текст на табличках не отображается в принципе с включенном модом.
Выключаю мод, перезахожу на сервер, таблички отображаются.

У меня почему то подозрения идут на приколы с содиумом, и траблами связанные с введением оптимизации джава в новых драйверах nvidia. Но вроде как эти приколы пофиксили ещё в 0.4.7 версии в декабре.

**Comment by feytox** [comment]
Прямо сейчас скачал FeyTweaks + Sodium. Всё отлично работает.
![изображение](https://github.com/feytox/FeyTweaks/assets/73577753/deabd06a-7c3c-4650-8124-35b6e708e0e4)

Ещё раз перепроверьте настройки мода, сбросьте всё на дефолт и сообщите результат.
Настройки мода, если что, выглядят так:
![изображение](https://github.com/feytox/FeyTweaks/assets/73577753/b3feebf8-a99a-4aa5-9f21-bc827577418c)

Если ничего не поможет, то посмотрите, точно ли нет никаких несовместимостей. Если же всё равно не работает, что очень-очень странно, используйте данный мод, который не совместим с этим, но тоже может оптимизировать таблички: https://modrinth.com/mod/immediatelyfast

**Comment by xMimicria** [comment]
Посбрасывал конфиги. Фулл чистую сборку собрал трижды. Результат один и тот же.

**Comment by DearFox** [comment]
Найдите в этом плюс - теперь текст на табличках не будет вызывать лаги вообще
И если вы стример, то это тоже большой плюс, что никто не забанит вас табличкой 
И да, а вы точно уверены что на этих табличках есть текст?
И нету ли в моде настройки скрывать текст табличек всегда, проверьте, мало ли.
И протестируйте в одиночном мире с одной табличкой, может быть условия сломались 
Ну и на крайний случай обновите Линукс, если не поможет то переустановите.
